site_name: 仓库
repo_url: https://github.com/zoeplus/mkdocslearn
repo_name: mkdocslearn
edit_uri: /main/docs/
site_description: 存放一些笔记
site_author: zoeplus

nav:
  - Introduction: 'index.md'
  - Math:
    - 'workon.md'
  - 'Find me elsewhere':
    - HackerRank: 'https://www.hackerrank.com/profile/zoepeace622'
    - Kaggle: 'https://www.kaggle.com/zoepeace' 

plugins:
  - search
  - git-revision-date

theme:
  name: material
  locale: en
  font:
    code: Roboto Mono
  features:
    - revision.date
    - revision.histor

extra_css:
  - stylesheets/extra.css
